# Generated by Django 3.1.5 on 2022-10-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0003_auto_20221025_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqs.option'),
        ),
    ]
