# Generated by Django 3.1.5 on 2022-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0004_auto_20221026_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mac_address',
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
    ]
