# Generated by Django 3.2.16 on 2022-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0009_submission_create_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='create_date_time',
        ),
        migrations.AddField(
            model_name='submission',
            name='qno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
