# Generated by Django 4.2.1 on 2023-05-27 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0010_auto_20221030_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='time',
            field=models.DurationField(default=datetime.timedelta(seconds=9000)),
        ),
    ]
