# Generated by Django 4.2.1 on 2023-05-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0011_candidate_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=100)),
                ('validity_start', models.DateTimeField()),
                ('validty_end', models.DateTimeField()),
            ],
        ),
    ]
