# Generated by Django 4.2.1 on 2023-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0012_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='passkey',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
