# Generated by Django 4.2.1 on 2023-05-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0013_passkey_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passkey',
            old_name='validty_end',
            new_name='validity_end',
        ),
    ]
