# Generated by Django 4.2.1 on 2023-06-03 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0014_rename_validty_end_passkey_validity_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
